# Generated by Django 2.0.7 on 2018-07-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='author',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
