# Generated by Django 2.0.7 on 2018-07-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0003_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='likes',
            field=models.CharField(max_length=255),
        ),
    ]
