# Generated by Django 2.0.7 on 2018-07-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180720_1438'),
        ('quotes', '0005_auto_20180720_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='quote_likes',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user_likes',
        ),
        migrations.AddField(
            model_name='quote',
            name='user_likes',
            field=models.ManyToManyField(related_name='quote_likes', to='users.User'),
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
