# Generated by Django 2.0.7 on 2018-07-17 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='ninja',
            new_name='dojo',
        ),
    ]
