# Generated by Django 2.0.7 on 2018-07-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas', '0002_auto_20180717_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
