# Generated by Django 2.0.7 on 2018-07-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user_jobs',
            field=models.ManyToManyField(related_name='jobs_for_user', to='login.User'),
        ),
    ]
